import type { RunProgress } from '../contracts/api-v1'

const STATIC_EVIDENCE = 'Functional tests unavailable — uploaded code was not executed. Syntax and scanner evidence are saved; choose repair strategies to continue.'

const LABELS: Record<RunProgress['stage'], string> = {
  queued: 'Preparing the local run', baseline_testing: 'Validating uploaded syntax', baseline_scanning: 'Running Bandit and Semgrep', awaiting_strategy: 'Baseline evidence is ready', repairing: 'Repairing code', repaired_testing: 'Checking repaired code', repaired_scanning: 'Scanning repaired code', reviewing: 'Reviewing evidence', reporting: 'Saving results', completed: 'Results ready', failed: 'Analysis failed', cancelled: 'Analysis cancelled',
}

export function AnalysisProgressScreen({ mode, progress, error, terminalMessage, onDone, onBack, onCancel }: {
  mode: 'upload' | 'custom'
  progress: RunProgress | null
  error: string | null
  terminalMessage: string | null
  onDone: () => void
  onBack: () => void
  onCancel: () => void
}) {
  const ready = progress?.stage === 'awaiting_strategy'
  const terminal = progress?.status === 'failed' || progress?.status === 'cancelled'
  const findings = progress?.baseline_findings ?? null
  const source = progress?.baseline_source ?? null
  const evidenceReady = mode === 'upload' && ready && findings !== null && Boolean(source) && Boolean(progress?.baseline_tests)

  if (evidenceReady) {
    const bandit = findings.filter(finding => finding.scanner === 'bandit').length
    const semgrep = findings.filter(finding => finding.scanner === 'semgrep').length
    return <div data-testid="upload-result-state" data-state="initial-scan" className="mx-auto flex w-full max-w-[1440px] flex-1 flex-col px-4 py-7 sm:px-6 lg:px-[72px] lg:py-8">
      <header><span className="rounded-full bg-[#171B21] px-3 py-1.5 font-mono text-[10px] font-semibold tracking-wide text-[#5EA7FF]">Exploratory upload analysis</span><h1 className="mt-3 text-3xl font-semibold tracking-[-0.03em] text-white sm:text-[34px]">Code Analysis Results</h1><p className="mt-2 text-sm leading-6 text-[#B8BEC7]">Review what Bandit and Semgrep found in the pasted or uploaded Python. These results are not part of the official benchmark.</p></header>
      <section className="mt-4 rounded-[14px] border border-[#2A3038] bg-[#12151A] px-4 py-3"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#5EA7FF]" /><h2 className="text-xs font-semibold text-white">What this page is for</h2></div><p className="mt-1.5 text-[11px] leading-5 text-[#AEB4BE]">This initial result shows the actual static scan. From here, you can optionally ask the backend AI for a repair and compare before vs. after.</p></section>
      <section className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl border border-[#2A3038] bg-[#12151A] p-4"><p className="font-mono text-[9px] text-[#7F8792]">FINDINGS FOUND</p><p className="mt-2 text-lg font-semibold text-[#FF8A2F]">{findings.length}</p><p className="mt-1 text-[10px] text-[#7F8792]">Bandit {bandit} · Semgrep {semgrep}</p></div><div className="rounded-xl border border-[#2A3038] bg-[#12151A] p-4"><p className="font-mono text-[9px] text-[#7F8792]">EXECUTION</p><p className="mt-2 text-lg font-semibold text-white">Static only</p><p className="mt-1 text-[10px] text-[#7F8792]">Uploaded code did not run</p></div><div className="rounded-xl border border-[#2A3038] bg-[#12151A] p-4"><p className="font-mono text-[9px] text-[#7F8792]">SYNTAX</p><p className="mt-2 text-lg font-semibold text-[#44D17A]">{progress?.baseline_syntax?.valid ? 'Syntax valid' : 'Unavailable'}</p></div><div className="rounded-xl border border-[#2A3038] bg-[#12151A] p-4"><p className="font-mono text-[9px] text-[#7F8792]">NEXT STEP</p><p className="mt-2 text-lg font-semibold text-[#44D17A]">Optional AI repair</p></div></section>
      <p className="mt-3 text-[11px] text-[#7F8792]">{STATIC_EVIDENCE}</p>
      <section className="mt-3 grid gap-3 lg:grid-cols-[minmax(0,1.4fr)_minmax(300px,0.9fr)]">
        <div className="space-y-3"><article className="overflow-hidden rounded-xl border border-[#2A3038] bg-[#12151A]"><div className="border-b border-[#2A3038] px-4 py-3"><h2 className="text-xs font-semibold text-white">Original uploaded code</h2></div><pre className="max-h-[250px] overflow-auto bg-[#0B0D10] p-4 font-mono text-[11px] leading-5 text-[#C9CDD3]"><code>{source}</code></pre></article><section className="rounded-xl border border-[#2A3038] bg-[#12151A] p-4"><h2 className="text-sm font-semibold text-white">Security findings</h2><div className="mt-3 max-h-[240px] space-y-2 overflow-auto">{findings.length ? findings.map(finding => <article key={finding.finding_id} className="rounded-lg border border-[#303741] bg-[#0B0D10] p-3"><p className="font-mono text-[10px] text-[#FF9A52]">{finding.scanner === 'bandit' ? 'Bandit' : 'Semgrep'} · {finding.rule_id}</p><p className="mt-1 text-[11px] leading-5 text-[#B8BEC7]">{finding.message}</p></article>) : <p className="rounded-lg border border-[#303741] bg-[#0B0D10] p-3 text-xs text-[#9CA3AF]">No findings were reported by the completed scanners.</p>}</div></section></div>
        <aside className="rounded-xl border border-[#2A3038] bg-[#12151A] p-4"><h2 className="text-sm font-semibold text-white">What can you do next?</h2><ol className="mt-3 list-decimal space-y-1 pl-4 text-xs leading-5 text-[#B8BEC7]"><li>Review the scanner warnings</li><li>Choose Repair with AI</li><li>Run one or more repair strategies</li><li>Compare findings before and after</li></ol><button type="button" onClick={onDone} className="mt-6 rounded-[10px] bg-[#FF7A1A] px-5 py-3 text-sm font-semibold text-[#0B0D10]">Repair with AI</button><button type="button" onClick={onBack} className="ml-2 mt-6 rounded-[10px] border border-[#3A414B] px-4 py-3 text-xs text-white">Analyze new code</button><p className="mt-4 text-[10px] leading-4 text-[#5EA7FF]">Exploratory only — never included in official benchmark rankings.</p></aside>
      </section>
      <p className="mt-3 text-[10px] leading-4 text-[#69717D]">Bandit and Semgrep inspect the source without running it. Static evidence is useful, not a security guarantee.</p>
    </div>
  }

  return <div className="mx-auto flex w-full max-w-[1296px] flex-1 flex-col justify-center px-4 py-10 sm:px-6"><div className="mx-auto w-full max-w-3xl"><p className="font-mono text-[10px] tracking-[0.18em] text-[#FF7A1A]">EXPLORATORY ANALYSIS</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.03em] text-white">{mode === 'upload' ? 'Analyze Your Code' : 'Generate & Evaluate'}</h1><p className="mt-3 text-sm leading-6 text-[#9CA3AF]">{mode === 'upload' ? 'Bandit and Semgrep are inspecting the uploaded source without running it.' : 'The backend is generating code, smoke-checking it, and collecting scanner evidence.'}</p><section className="mt-7 rounded-xl border border-[#2A3038] bg-[#12151A] p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-medium text-white">{progress ? LABELS[progress.stage] : 'Connecting to the local backend'}</p><p className="mt-1 font-mono text-[10px] text-[#737B87]">{progress?.run_id ?? 'Run ID pending'}</p></div><span className={`rounded-full border px-2.5 py-1 font-mono text-[9px] ${terminal ? 'border-red-500/30 text-red-300' : 'border-[#FF7A1A]/35 text-[#FF9A52]'}`}>{terminal ? progress?.status.toUpperCase() : 'WORKING'}</span></div>{!terminal && <div className="mt-5 h-1.5 overflow-hidden rounded-full bg-[#252B33]"><div className="h-full w-1/2 animate-pulse rounded-full bg-[#FF7A1A]" /></div>}{(error || terminalMessage) && <p role="alert" className="mt-5 rounded-lg border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{error || terminalMessage}</p>}{ready && !evidenceReady && <p role="alert" className="mt-5 text-xs text-amber-200">Baseline processing finished, but its persisted evidence is unavailable. No placeholder result is shown.</p>}<div className="mt-6 flex flex-wrap justify-end gap-3">{terminal ? <button type="button" onClick={onBack} className="rounded-lg border border-[#3A414B] px-4 py-2.5 text-xs text-[#D4D7DC]">Back</button> : <button type="button" onClick={onCancel} className="rounded-lg border border-[#3A414B] px-4 py-2.5 text-xs text-[#D4D7DC]">Cancel</button>}</div></section></div></div>
}